version: '3'
services:
    vote:
        image: dockersamples/examplevotingapp_vote:before
        ports:
            - 5000:80
        networks:
            - frontend
    redis:
        image: redis:3.2
        networks:
            - frontend
    worker:
        image: dockersamples/examplevotingapp_worker
        networks:
            - frontend
            - backend
    db:
        image: postgres:9.4
        networks:
            - backend
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            - POSTRES_HOST_AUTH_METHOD=trust
    result:
        image: dockersamples/examplevotingapp_result:before
        ports:
            - 5001:80
        networks:
            - backend
volumes:
    dbdata:
networks:
    frontend:
    backend:
