version: '3'
services:
    drupal:
        build: .
        image: jshafto/custom-drupal
        ports:
            - 8080:80
        depends_on:
            - "db"
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=password
        volumes:
            - drupal-data:/var/lib/postgresql/data
volumes:
    drupal-data:
